In [1]:
arquivo = open(r"data\dom_casmurro.txt", encoding="utf-8")

texto = arquivo.read().lower()

In [2]:
palavras = texto.split()
len(palavras)

65707

In [3]:
import pandas as pd
tabela = pd.DataFrame({"palavra":palavras})
tabela.head()

    palavra
0       dom
1  casmurro
2       por
3   machado
4        de

In [4]:
tabela["proxima_palavra"] = tabela["palavra"].shift(-1)
tabela

        palavra proxima_palavra
0           dom        casmurro
1      casmurro             por
2           por         machado
3       machado              de
4            de           assis
...         ...             ...
65702         é            bem,
65703      bem,               e
65704         e               o
65705         o          resto?
65706    resto?             NaN

[65707 rows x 2 columns]

In [5]:
tabela = tabela.dropna()
tabela

        palavra proxima_palavra
0           dom        casmurro
1      casmurro             por
2           por         machado
3       machado              de
4            de           assis
...         ...             ...
65701   cxlviii               é
65702         é            bem,
65703      bem,               e
65704         e               o
65705         o          resto?

[65706 rows x 2 columns]

In [55]:
filtro = tabela["palavra"] == "mãe"
tabela[filtro]

      palavra proxima_palavra
1185      mãe            quiz
1671      mãe       assoou-se
2292      mãe       ficou-lhe
2542      mãe        dava-lhe
2698      mãe             lhe
...       ...             ...
62877     mãe        embarcou
63188     mãe             lhe
63528     mãe         morreu,
64008     mãe          falava
65224     mãe               e

[126 rows x 2 columns]

In [56]:
tabela[filtro]["proxima_palavra"].value_counts(normalize=True)

proxima_palavra
e           0.095238
que         0.071429
era         0.063492
não         0.039683
lhe         0.031746
              ...
estava      0.007937
menos       0.007937
embarcou    0.007937
morreu,     0.007937
falava      0.007937
Name: proportion, Length: 82, dtype: float64

In [57]:
tabela[filtro]["proxima_palavra"].value_counts().idxmax()

'e'